{{- if .Values.global.rbacEnabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-sidecar-injector-admin-role-binding-{{ .Release.Namespace }}
  labels:
    app: istio-sidecar-injector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.global.k8sAddon.enabled }}
    k8s-app: istio
    addonmanager.kubernetes.io/mode: Reconcile
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-sidecar-injector-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istio-sidecar-injector-service-account
    namespace: {{ .Release.Namespace }}
{{- end }}