apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    istio: sidecar-injector
  {{- if .Values.global.k8sAddon.enabled }}
    k8s-app: istio
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  {{- end }}
spec:
  ports:
  - port: 443
  selector:
    istio: sidecar-injector
