{{- if .Values.autoscaleMin }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.service.name }}
    namespace: {{ .Values.service.namespace | default .Release.Namespace }}
  {{- if .Values.global.k8sAddon.enabled }}
    labels:
      k8s-app: istio
      addonmanager.kubernetes.io/mode: Reconcile
  {{- end }}

spec:
    maxReplicas: {{ .Values.autoscaleMax }}
    minReplicas: {{ .Values.autoscaleMin }}
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: {{ .Values.service.name }}
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 80
{{ end }}
