apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 2 }}
{{- end }}
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.k8sAddon.enabled }}
  labels:
    k8s-app: istio
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
