apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-statsd-prom-bridge
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-statsd-prom-bridge
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    istio: mixer
  {{- if .Values.global.k8sAddon.enabled }}
    k8s-app: istio
    addonmanager.kubernetes.io/mode: Reconcile
  {{- end }}
data:
  mapping.conf: |-
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-mixer-custom-resources
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-mixer
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    istio: mixer
{{- if .Values.global.k8sAddon.enabled }}
    k8s-app: istio
    addonmanager.kubernetes.io/mode: Reconcile
{{- end }}
data:
  custom-resources.yaml: |-
    {{- include "config.yaml.tpl" . | indent 4}}
