apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-galley-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-galley
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.global.k8sAddon.enabled }}
    k8s-app: istio
    addonmanager.kubernetes.io/mode: Reconcile
  {{- end }}
